### ISSUE TITLE
Add BUSCO?

### ISSUE THREAD

**Issue by boulund** [KThorellGroup/BACTpipe#103]
https://gitlab.com/ezlab/busco

**Comment by boulund** [comment]
@thorellk mentioned BUSCO might not support bacteria. There is something bacteria-related on their webpage, but I actually have no clue about how to use BUSCO at all. I guess I have some reading to do.
https://busco.ezlab.org/

**Comment by thorellk** [comment]
I think this is outside of the scope as of now. Maybe for the future?

**Comment by abhi18av** [comment]
Hi @thorellk , glad to see activity in this repo again :)
